services:
  director:
    image: public.ecr.aws/sandgarden/sgdirector:latest
    environment:
      - SAND_LOG_LEVEL=debug
      - SAND_API_KEY=${SAND_API_KEY}
      - SAND_HOME=/.sandgarden
      - SAND_CLUSTER=getting-started
      - SAND_DEFAULT_DOCKER_PLATFORM=linux/arm64
    ports:
      - "8987:8987"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../:/workspaces/sandgarden
      - .sandgarden:/.sandgarden
